///////////////////////////////////
///////// TACOS DB JSON //////////
/////////////////////////////////

export const tacos = [
  {
    _id: "taco001",
    name: "Classic Al Pastor",
    primaryProtein: "pork",
    cuisineRegion: "Mexico City",
    loves: ["pineapple", "cilantro", "onions"],
    spiceLevel: 6,
    preparationStyle: "spit-roasted",
    weight: 250,
    popularityRating: 9,
    priceRange: "$3-5",
    accompaniments: ["lime", "salsa verde"],
  },
  {
    _id: "taco002",
    name: "Mac & Cheese Madness",
    primaryProtein: "pulled chicken",
    cuisineRegion: "Fusion Americana",
    loves: ["mac and cheese", "crispy bacon", "green onions"],
    spiceLevel: 3,
    preparationStyle: "deep-fried",
    weight: 350,
    popularityRating: 7,
    priceRange: "$6-8",
    accompaniments: ["ranch dressing", "hot sauce"],
  },
  {
    _id: "taco003",
    name: "Sushi Tsunami Taco",
    primaryProtein: "raw salmon",
    cuisineRegion: "Pacific Fusion",
    loves: ["sushi rice", "seaweed", "wasabi mayo"],
    spiceLevel: 4,
    preparationStyle: "raw",
    weight: 200,
    popularityRating: 8,
    priceRange: "$9-12",
    accompaniments: ["pickled ginger", "soy sauce"],
  },
  {
    _id: "taco004",
    name: "Jackfruit Revolucion",
    primaryProtein: "jackfruit",
    cuisineRegion: "Vegan Street",
    loves: ["BBQ sauce", "coleslaw", "crispy onions"],
    spiceLevel: 5,
    preparationStyle: "slow-cooked",
    weight: 275,
    popularityRating: 7,
    priceRange: "$7-9",
    accompaniments: ["vegan crema", "lime"],
  },
  {
    _id: "taco005",
    name: "Breakfast Burrito Bomb",
    primaryProtein: "scrambled eggs",
    cuisineRegion: "Brunch Boulevard",
    loves: ["hash browns", "bacon bits", "cheese"],
    spiceLevel: 4,
    preparationStyle: "grilled",
    weight: 400,
    popularityRating: 8,
    priceRange: "$6-8",
    accompaniments: ["hot sauce", "sour cream"],
  },
  {
    _id: "taco006",
    name: "Carnitas Classico",
    primaryProtein: "braised pork",
    cuisineRegion: "Michoacán, Mexico",
    loves: ["cilantro", "diced onions", "lime"],
    spiceLevel: 5,
    preparationStyle: "slow-roasted",
    weight: 300,
    popularityRating: 9,
    priceRange: "$4-6",
    accompaniments: ["salsa roja", "guacamole"],
  },
  {
    _id: "taco007",
    name: "Pineapple Apocalypse",
    primaryProtein: "al pastor pork",
    cuisineRegion: "Tropical Fusion",
    loves: ["caramelized pineapple", "habanero sauce", "mint"],
    spiceLevel: 8,
    preparationStyle: "flame-grilled",
    weight: 225,
    popularityRating: 6,
    priceRange: "$7-9",
    accompaniments: ["cooling cucumber", "tropical salsa"],
  },
  {
    _id: "taco008",
    name: "Impossible Korean BBQ",
    primaryProtein: "Impossible meat",
    cuisineRegion: "K-Town Fusion",
    loves: ["kimchi", "gochujang", "sesame seeds"],
    spiceLevel: 7,
    preparationStyle: "wok-seared",
    weight: 280,
    popularityRating: 8,
    priceRange: "$8-10",
    accompaniments: ["korean pickles", "green onions"],
  },
  {
    _id: "taco009",
    name: "Dessert Taco Insanity",
    primaryProtein: "chocolate mousse",
    cuisineRegion: "Sweet Street",
    loves: ["strawberries", "whipped cream", "chocolate chips"],
    spiceLevel: 1,
    preparationStyle: "no-cook",
    weight: 200,
    popularityRating: 7,
    priceRange: "$5-7",
    accompaniments: ["caramel sauce", "mint leaf"],
  },
  {
    _id: "taco010",
    name: "Buffalo Cauliflower Crunch",
    primaryProtein: "cauliflower",
    cuisineRegion: "Veggie Vibes",
    loves: ["buffalo sauce", "blue cheese crumbles", "celery"],
    spiceLevel: 6,
    preparationStyle: "roasted",
    weight: 250,
    popularityRating: 7,
    priceRange: "$6-8",
    accompaniments: ["ranch", "green onions"],
  },
  {
    _id: "taco011",
    name: "Mediterranean Lamb Dream",
    primaryProtein: "lamb",
    cuisineRegion: "Mediterranean Fusion",
    loves: ["tzatziki", "feta", "mint"],
    spiceLevel: 4,
    preparationStyle: "grilled",
    weight: 325,
    popularityRating: 8,
    priceRange: "$9-11",
    accompaniments: ["cucumber", "olive tapenade"],
  },
  {
    _id: "taco012",
    name: "Truffle Shuffle Taco",
    primaryProtein: "wild mushroom",
    cuisineRegion: "Gourmet Galaxy",
    loves: ["truffle oil", "parmesan", "arugula"],
    spiceLevel: 2,
    preparationStyle: "sautéed",
    weight: 275,
    popularityRating: 6,
    priceRange: "$10-13",
    accompaniments: ["herb aioli", "crispy shallots"],
  },
];
