/////////////////////////////////////
///////// Turtles DB JSON //////////
///////////////////////////////////

export const turtles = [
  {
    _id: "turtle001",
    name: "Sheldon",
    species: "Loggerhead Sea Turtle",
    habitat: "Atlantic Ocean",
    loves: ["blue crabs", "jellyfish", "squid"],
    dob: "1985-06-15T10:30:00.000Z",
    weight: 350,
    gender: "m",
    shellWidth: 95,
    conservationStatus: "Vulnerable",
    kilometresMigrated: 4200,
  },
  {
    _id: "turtle002",
    name: "Marina",
    species: "Green Sea Turtle",
    habitat: "Pacific Ocean",
    loves: ["seagrass", "algae", "small fish"],
    dob: "1990-03-22T14:45:00.000Z",
    weight: 285,
    gender: "f",
    shellWidth: 80,
    conservationStatus: "Endangered",
    kilometresMigrated: 3750,
  },
  {
    _id: "turtle003",
    name: "Franklin",
    species: "Box Turtle",
    habitat: "North American Forests",
    loves: ["berries", "worms", "mushrooms"],
    dob: "1995-11-07T09:15:00.000Z",
    weight: 450,
    gender: "m",
    shellWidth: 120,
    conservationStatus: "Least Concern",
    kilometresMigrated: 12,
  },
  {
    _id: "turtle004",
    name: "Reef",
    species: "Hawksbill Sea Turtle",
    habitat: "Caribbean Sea",
    loves: ["sponges", "marine invertebrates", "coral"],
    dob: "1988-07-30T16:20:00.000Z",
    weight: 95,
    gender: "f",
    shellWidth: 70,
    conservationStatus: "Critically Endangered",
    kilometresMigrated: 5600,
  },
  {
    _id: "turtle005",
    name: "Terra",
    species: "Galapagos Giant Tortoise",
    habitat: "Galapagos Islands",
    loves: ["cactus pads", "grasses", "fruits"],
    dob: "1965-04-12T11:55:00.000Z",
    weight: 250,
    gender: "f",
    shellWidth: 150,
    conservationStatus: "Vulnerable",
    kilometresMigrated: 2,
  },
  {
    _id: "turtle006",
    name: "Tsunami",
    species: "Leatherback Sea Turtle",
    habitat: "Indian Ocean",
    loves: ["jellyfish", "salps", "squid"],
    dob: "1979-09-18T03:40:00.000Z",
    weight: 700,
    gender: "m",
    shellWidth: 200,
    conservationStatus: "Vulnerable",
    kilometresMigrated: 8900,
  },
  {
    _id: "turtle007",
    name: "Crush",
    species: "Olive Ridley Sea Turtle",
    habitat: "Eastern Pacific",
    loves: ["crabs", "shrimp", "small fish"],
    dob: "1992-12-05T20:10:00.000Z",
    weight: 45,
    gender: "m",
    shellWidth: 65,
    conservationStatus: "Vulnerable",
    kilometresMigrated: 6300,
  },
  {
    _id: "turtle008",
    name: "Sage",
    species: "Painted Turtle",
    habitat: "North American Lakes",
    loves: ["aquatic insects", "small fish", "algae"],
    dob: "1998-02-14T13:25:00.000Z",
    weight: 500,
    gender: "f",
    shellWidth: 110,
    conservationStatus: "Least Concern",
    kilometresMigrated: 25,
  },
  {
    _id: "turtle009",
    name: "Neptune",
    species: "Kemp's Ridley Sea Turtle",
    habitat: "Gulf of Mexico",
    loves: ["crabs", "shrimp", "jellyfish"],
    dob: "1975-06-08T07:50:00.000Z",
    weight: 40,
    gender: "m",
    shellWidth: 60,
    conservationStatus: "Critically Endangered",
    kilometresMigrated: 4500,
  },
  {
    _id: "turtle010",
    name: "River",
    species: "Painted River Turtle",
    habitat: "Southeast Asian Rivers",
    loves: ["snails", "aquatic plants", "small crustaceans"],
    dob: "1987-10-22T15:35:00.000Z",
    weight: 5,
    gender: "f",
    shellWidth: 25,
    conservationStatus: "Endangered",
    kilometresMigrated: 100,
  },
  {
    _id: "turtle011",
    name: "Coral",
    species: "Flatback Sea Turtle",
    habitat: "Australian Coastline",
    loves: ["soft-bodied invertebrates", "sea cucumbers", "jellyfish"],
    dob: "1993-05-17T18:45:00.000Z",
    weight: 90,
    gender: "f",
    shellWidth: 75,
    conservationStatus: "Data Deficient",
    kilometresMigrated: 3200,
  },
  {
    _id: "turtle012",
    name: "Rocky",
    species: "Wood Turtle",
    habitat: "North American Forests and Streams",
    loves: ["earthworms", "slugs", "berries"],
    dob: "1980-08-03T12:20:00.000Z",
    weight: 1100,
    gender: "m",
    shellWidth: 140,
    conservationStatus: "Endangered",
    kilometresMigrated: 50,
  },
];
